apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-storage-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
      - name: git-server
        image: gogs/gogs
        resources:
          limits:
            memory: "5Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        ports:
        - name: ssh
          containerPort: 22
        - name: webinterface
          containerPort: 3000
        volumeMounts:
          - name: git-data
            mountPath: /data
        securityContext:
          runAsUser: 0 # Container will be run as user root (otherwise change user id)
      volumes:
        - name: git-data
          persistentVolumeClaim:
            claimName: git-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: git-endpoint
spec:
  type: LoadBalancer
  ports:
    - name: webinterface
      port: 80
      targetPort: 3000
  selector:
    app: git-server