apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-persistent-storage-claim #  Name of the persistent volume claim
  annotations:
    volume.beta.kubernetes.io/storage-class: azuredisk  # Name of the Storage Class you want to use to dynamically get your storage
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce" | AzureDisk just support once and AzureFile support many
  resources:
    requests:
      storage: 50Gi # How much storage do you want for your claim
