apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  labels:
    app: busybox
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
