apiVersion: v1
kind: Pod
metadata:
  name: __PodName__
spec:
  containers:
  - name: __PodName__
    image: centos:latest
    command: [ "/bin/bash" ]
    args: ["-c", 'run=1; while true; do echo "This is the $run run and I am still alive!"; run=$((run+1)); sleep 3; done']
  tolerations:
  - key: "virtual-kubelet.io/provider"
    operator: Equal
    value: "azure"
  restartPolicy: Never
