apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistenenv
  labels:
    app: testenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testenv
  template:
    metadata:
      labels:
        app: testenv
    spec:
      containers:
      - name: testenv
        image: centos:latest
        command: ["/bin/bash", "-c", "cat"]
      tolerations:
      - key: "virtual-kubelet.io/provider"
        operator: Equal
        value: "azure"
